enabled: true
expire_password: true
first_time_login_password_change: true
installation_date: 1543322410
check_login_only: false
_core:
  default_config_hash: Lmq0hGaFh0zNyozQ2r61-vypLNm7zYcmI6DhSwV5cGU
langcode: fr
